<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>ToMauScraper</AssemblyName>
    <RootNamespace>ToMauScraper</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>8.0</LangVersion>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <Version>1.0.7</Version>
    <FileVersion>1.0.7.0</FileVersion>
    <AssemblyVersion>1.0.7.0</AssemblyVersion>
    <Product>ToMau.vn Scraper</Product>
    <AssemblyTitle>ToMau.vn Scraper</AssemblyTitle>
    <Description>Tool tìm kiếm, xem trước, in và tải tranh tô màu từ tomau.vn</Description>
    <Copyright>Copyright © 2026 ThanhNguyenVN93</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>

</Project>
